apiVersion: aws.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
spec:
  credentials:
    source: InjectedIdentity
---
apiVersion: kubernetes.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: kubernetes-provider
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: kubeconfig-crossplane-eks-cluster-dwight-8vbsp
      key: kubeconfig
# identity:
#   type: GoogleApplicationCredentials
#   source: Secret
#   secretRef:
#     name: gcp-credentials
#     namespace: crossplane-system
#     key: credentials.json
---
apiVersion: helm.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: helm-provider
spec:
  credentials:
    source: Secret
    secretRef:
      name: kubeconfig-crossplane-eks-cluster-dwight-8vbsp
      namespace: crossplane-system
      key: kubeconfig
# identity:
#   type: GoogleApplicationCredentials
#   source: Secret
#   secretRef:
#     name: gcp-credentials
#     namespace: crossplane-system
#     key: credentials.json