---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xbuckets.s3bucket.bigbang.dev
  labels:
    provider: crossplane-provider-aws
spec:
  compositeTypeRef:
    apiVersion: s3bucket.bigbang.dev/v1alpha1
    kind: XBucket
  resources:
    - name: bucket
      base:
        apiVersion: s3.aws.crossplane.io/v1beta1
        kind: Bucket
        spec:
          deletionPolicy: Delete          
          forProvider:
            serverSideEncryptionConfiguration:
              rules:
                - applyServerSideEncryptionByDefault:
                    sseAlgorithm: AES256
          providerConfigRef:
            name: default
      patches:
        - fromFieldPath: "status.atProvider.arn"
          toFieldPath: "status.bucketArn"
          type: ToCompositeFieldPath
        - fromFieldPath: "spec.parameters.bucketName"
          toFieldPath: "metadata.name"
        - fromFieldPath: "metadata.annotations.crossplane.io/external-name"
          toFieldPath: "metadata.annotations.crossplane.io/external-name"
        - fromFieldPath: "spec.parameters.region"
          toFieldPath: "spec.forProvider.locationConstraint"
    - name: bucketpolicy
      base:
        apiVersion: s3.aws.crossplane.io/v1alpha3
        kind: BucketPolicy
        spec:
          deletionPolicy: Delete          
          forProvider:
            policy:
              version: "2012-10-17"
              statements:
                - effect: "Allow"
                  action:
                    - "s3:GetObject"
                    - "s3:PutObject"
                  principal:
                    awsPrincipals:
                      - awsAccountId: "950698127059"
          providerConfigRef:
            name: default
      patches:
        - fromFieldPath: "status.bucketArn"
          toFieldPath: "spec.forProvider.policy.statements[0].resource[0]"
          transforms:
            - type: string
              string:
                fmt: "%s/*"
        - fromFieldPath: "spec.parameters.bucketName"
          toFieldPath: "spec.forProvider.bucketName"
        - fromFieldPath: "metadata.annotations.crossplane.io/external-name"
          toFieldPath: "metadata.annotations.crossplane.io/external-name"
        - fromFieldPath: "spec.parameters.region"
          toFieldPath: "spec.forProvider.region"