apiVersion: infra.bigbang.dev/v1alpha1
kind: Enclave
metadata:
  name: dwight-enclave
  namespace: default
spec:
  parameters:
    region: us-east-1
    availabilityZone1: us-east-1a
    availabilityZone2: us-east-1b
    availabilityZone3: us-east-1c
  compositionSelector:
    matchLabels:
      provider: aws
---
apiVersion: infra.bigbang.dev/v1alpha1
kind: EKSCluster
metadata:
  name: crossplane-eks-cluster-dwight
  namespace: default
spec:
  parameters:
    region: us-east-1
    k8sVersion: "1.22"
    subnetMatchLabels:
      crossplane.io/claim-name: dwight-enclave
      crossplane.io/claim-namespace: default
      visibility: public
  compositionSelector:
    matchLabels:
      provider: aws
---
apiVersion: infra.bigbang.dev/v1alpha1
kind: EKSManagedNodeGroup
metadata:
  name: crossplane-eks-cluster-dwight-with-managed-nodegroup
  namespace: default
spec:
  parameters:
    region: us-east-1
    clusterNameMatchLabels:
      crossplane.io/claim-name: crossplane-eks-cluster-dwight
      crossplane.io/claim-namespace: default
    diskSize: 20
    instanceTypes:
      - t3.medium
    desiredNodeCount: 3
    minNodeCount: 3
    maxNodeCount: 5
    subnetMatchLabels:
      crossplane.io/claim-name: dwight-enclave
      crossplane.io/claim-namespace: default
      visibility: public
---
apiVersion: kubernetes.crossplane.io/v1alpha1
kind: Object
metadata:
  name: flux-system
spec:
  forProvider:
    manifest:
      apiVersion: v1
      kind: Namespace
      metadata:
  providerConfigRef:
    name: kubernetes-provider
---
apiVersion: helm.crossplane.io/v1beta1
kind: Release
metadata:
  name: fluxv2
spec:
# rollbackLimit: 3
  forProvider:
    chart:
      name: flux2
      repository: https://fluxcd-community.github.io/helm-charts
      version: 1.3.0
    namespace: flux-system
  providerConfigRef:
    name: helm-provider
---
apiVersion: kubernetes.crossplane.io/v1alpha1
kind: Object
metadata:
  name: podinfo
spec:
  forProvider:
    manifest:
      apiVersion: v1
      kind: Namespace
      metadata:
  providerConfigRef:
    name: kubernetes-provider
---
apiVersion: helm.crossplane.io/v1beta1
kind: Release
metadata:
  name: podinfo
spec:
# rollbackLimit: 3
  forProvider:
    chart:
      name: podinfo
      repository: https://stefanprodan.github.io/podinfo
      version: 6.2.0
    namespace: podinfo
  providerConfigRef:
    name: helm-provider