apiVersion: infra.bigbang.dev/v1alpha1
kind: Enclave
metadata:
  name: jim-enclave
  namespace: default
spec:
  parameters:
    region: us-east-1
    availabilityZone1: us-east-1a
    availabilityZone2: us-east-1b
    availabilityZone3: us-east-1c
  compositionSelector:
    matchLabels:
      provider: aws
---
apiVersion: infra.bigbang.dev/v1alpha1
kind: EKSCluster
metadata:
  name: crossplane-eks-cluster-jim
  namespace: default
spec:
  parameters:
    region: us-east-1
    k8sVersion: "1.23"
    subnetMatchLabels:
      crossplane.io/claim-name: jim-enclave
      crossplane.io/claim-namespace: default
      visibility: public
  compositionSelector:
    matchLabels:
      provider: aws
