apiVersion: infra.bigbang.dev/v1alpha1
kind: Enclave
metadata:
  name: dwight-enclave
  namespace: default
spec:
  parameters:
    region: us-east-1
    availabilityZone1: us-east-1a
    availabilityZone2: us-east-1b
    availabilityZone3: us-east-1c
  compositionSelector:
    matchLabels:
      provider: crossplane-provider-aws
---
apiVersion: infra.bigbang.dev/v1alpha1
kind: EKSCluster
metadata:
  name: crossplane-eks-cluster-dwight
  namespace: default
spec:
  parameters:
    region: us-east-1
    k8sVersion: "1.22"
    subnetMatchLabels:
      crossplane.io/claim-name: dwight-enclave
      crossplane.io/claim-namespace: default
      visibility: public
  compositionSelector:
    matchLabels:
      provider: crossplane-provider-aws
---
apiVersion: infra.bigbang.dev/v1alpha1
kind: EKSManagedNodeGroup
metadata:
  name: crossplane-eks-cluster-dwight-with-managed-nodegroup
  namespace: default
spec:
  parameters:
    region: us-east-1
    clusterNameMatchLabels:
      crossplane.io/claim-name: crossplane-eks-cluster-dwight
      crossplane.io/claim-namespace: default
    diskSize: 20
    instanceTypes:
      - t3.medium
    desiredNodeCount: 3
    minNodeCount: 3
    maxNodeCount: 5
    subnetMatchLabels:
      crossplane.io/claim-name: dwight-enclave
      crossplane.io/claim-namespace: default
      visibility: public
---
apiVersion: databases.bigbang.dev/v1alpha1
kind: MySQLChildInstance
metadata:
  name: wordpress-mysql-rds
  namespace: default
spec:
  parameters:
    storageGB: 10
    region: us-east-1
    availabilityZone: us-east-1a
    dbName: wordpressdb
    dbInstanceClass: db.t3.medium
    dbSubnetGroupName: dwight-enclave-gq78z-sxpnp
    vpcId: vpc-0757e67d2aaa72fb7
  compositionSelector:
    matchLabels:
      provider: crossplane-provider-aws
  writeConnectionSecretToRef:
    name: mysql-rds

#The following objects are being deployed to spoke cluster dwight
---
apiVersion: kubernetes.crossplane.io/v1alpha1
kind: Object
metadata:
  name: flux-system
spec:
  forProvider:
    manifest:
      apiVersion: v1
      kind: Namespace
      metadata:
  providerConfigRef:
    name: kubernetes-provider
---
apiVersion: helm.crossplane.io/v1beta1
kind: Release
metadata:
  name: fluxv2
spec:
# rollbackLimit: 3
  forProvider:
    chart:
      name: flux2
      repository: https://fluxcd-community.github.io/helm-charts
      version: 1.3.0
    namespace: flux-system
  providerConfigRef:
    name: helm-provider
---
apiVersion: kubernetes.crossplane.io/v1alpha1
kind: Object
metadata:
  name: podinfo
spec:
  forProvider:
    manifest:
      apiVersion: v1
      kind: Namespace
      metadata:
  providerConfigRef:
    name: kubernetes-provider
---
apiVersion: helm.crossplane.io/v1beta1
kind: Release
metadata:
  name: podinfo
spec:
# rollbackLimit: 3
  forProvider:
    chart:
      name: podinfo
      repository: https://stefanprodan.github.io/podinfo
      version: 6.2.0
    namespace: podinfo
  providerConfigRef:
    name: helm-provider
---
apiVersion: kubernetes.crossplane.io/v1alpha1
kind: Object
metadata:
  name: wordpress
spec:
  forProvider:
    manifest:
      apiVersion: v1
      kind: Namespace
      metadata:
  providerConfigRef:
    name: kubernetes-provider
---
apiVersion: kubernetes.crossplane.io/v1alpha1
kind: Object
metadata:
  name: wordpress-git
spec:
  forProvider:
    manifest:
      apiVersion: source.toolkit.fluxcd.io/v1beta2
      kind: GitRepository
      metadata:
        name: wordpress
        namespace: wordpress
      spec:
        interval: 1m
        url: https://github.com/defenseunicorns/crossplane-rds-wordpress-demo.git
        ref:
          branch: demo
  providerConfigRef:
    name: kubernetes-provider
---
apiVersion: kubernetes.crossplane.io/v1alpha1
kind: Object
metadata:
  name: wordpress-hr
spec:
  forProvider:
    manifest:
      apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      metadata:
        name: wordpress
        namespace: wordpress
      spec:
        interval: 5m
        chart:
          spec:
            chart: wordpress
            version: "15.2.2"
            sourceRef:
              kind: GitRepository
              name: wordpress
              namespace: wordpress
            interval: 1m
  providerConfigRef:
    name: kubernetes-provider
---
apiVersion: s3bucket.bigbang.dev/v1alpha1
kind: Bucket
metadata:
  namespace: default
  name: test-s3-bucket-us-east-1
  annotations:
    crossplane.io/external-name: test-s3-bucket-us-east-1
spec:
  parameters:
    bucketName: test-s3-bucket-us-east-1
    region: us-east-1
  compositionSelector:
    matchLabels:
      provider: crossplane-provider-aws
---
apiVersion: kubernetes.crossplane.io/v1alpha1
kind: Object
metadata:
  name: dbpassword
spec:
  references:
  # Use patchesFrom to patch field from other k8s resource to this object
  - patchesFrom:
      apiVersion: v1
      kind: Secret
      name: mysql-rds
      namespace: default
      fieldPath: data.password
    toFieldPath: data.password
  forProvider:
    manifest:
      apiVersion: v1
      kind: Secret
      metadata:
        namespace: wordpress
        name: password
      data:
        password: sample-value
  providerConfigRef:
    name: kubernetes-provider